name: Release Build
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Application version'
        required: true
        default: '1.0'

jobs:
  Build:
    name: Build/Sign APK
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Get app name
        run: |
          # Extract version number from branch name
          version_name=$(grep app/build.gradle | tr -d '\n')

          # Get existing version code from build.gradle
          version_code=$(grep "versionCode" app/build.gradle | awk '{print $2}' | tr -d '\n')

          # Increment existing version code by 1
          version_code=$((version_code + 1))

          # Set environment variable for later use
          echo "VERSION_NAME=$version_name" >> $GITHUB_ENV
          echo "VERSION_CODE=$version_code" >> $GITHUB_ENV


      - name: Decode Keystore
        id: decode_keystore
        uses: timheuer/base64-to-file@v1.2
        with:
            fileName: 'android_keystore.jks'
            fileDir: '/home/runner/work/<<project name>>/<<project name>>/app/keystore/'
            encodedString: ${{ secrets.KEYSTORE }}
      - name: Build APK
        id: build
        run: bash ./gradlew assembleRelease -x test
        env:
          SIGNING_KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          SIGNING_KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
          SIGNING_STORE_PASSWORD: ${{ secrets.KEY_STORE_PASSWORD }}

      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: <<application name>>
          path: app/build/outputs/apk/release/<<application name>>_${{ github.event.inputs.version }}.apk

      - name: Upload S3
        uses: shallwefootball/s3-upload-action@master
        id: s3
        with:
          aws_key_id: ${{ secrets.AWS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
          aws_bucket: ${{ secrets.AWS_BUCKET }}
          source_dir: app/build/outputs/apk/release/<<application name>>_${{ github.event.inputs.version }}.apk
