name: Release Build
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Application version'
        required: true
        default: '1.0'

jobs:
  Build:
    name: Build/Sign APK
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2


      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Get app name
        run: |
          # Extract version number from branch name
          version_name=$(grep app/build.gradle | tr -d '\n')

          # Get existing version code from build.gradle
          version_code=$(grep "versionCode" app/build.gradle | awk '{print $2}' | tr -d '\n')

          # Increment existing version code by 1
          version_code=$((version_code + 1))

          # Set environment variable for later use
          echo "VERSION_NAME=$version_name" >> $GITHUB_ENV
          echo "VERSION_CODE=$version_code" >> $GITHUB_ENV

      - name: Build APK
        id: build
        run: bash ./gradlew assembleRelease -x test
        env:
          SIGNING_KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          SIGNING_KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
          SIGNING_STORE_PASSWORD: ${{ secrets.KEY_STORE_PASSWORD }}

      - name: Sign APK
        run: |
            wget https://github.com/appium/sign/archive/refs/heads/master.zip
            unzip master.zip
            cd sign-master
            
            cp github-actions-demo_2.0.apk ./
            cp app/src/platform.x509.pem ./
            cp app/src/platform.pk8 ./
            
            ./signapk.sh platform.x509.pem platform.pk8 github-actions-demo_2.0.apk  github-actions-demo_2.0_signed.apk

      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: release.zip
          path: app/build/outputs/apk/release/

      - name: Upload S3
        uses: shallwefootball/s3-upload-action@master
        id: s3
        with:
          aws_key_id: ${{ secrets.AWS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
          aws_bucket: ${{ secrets.AWS_BUCKET }}
          source_dir: app/build/outputs/apk/release/
          destination_dir: ''
