name: Release Build
on: workflow_dispatch
jobs:
  Build:
    name: Build/Sign APK
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Get Tag
        id: var
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}

      - name: Get app name
        run: |
          echo "app_name=${{steps.android_version.outputs.app_name}}" >> $GITHUB_ENV

      - name: Get version
        run: |
          echo "version_code=${{steps.android_version.outputs.version_code}}" >> $GITHUB_ENV

      - name: Build APK
        id: build
        run: bash ./gradlew assembleRelease

      - name: Sign APK
        id: sign_apk
        uses: r0adkll/sign-android-release@v1
        with:
          releaseDirectory: app/build/outputs/apk/release
          signingKeyBase64: ${{ secrets.KEYSTORE }}
          alias: ${{ secrets.KEY_ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}

      - name: Make artifact
        uses: actions/upload-artifact@v2
        with:
          name: app-release-signed
          path: ${{steps.sign_apk.outputs.signedReleaseFile}}

      - name: Build AAB
        run: bash ./gradlew bundleRelease

      - name: Sign AAB
        id: sign_aab
        uses: r0adkll/sign-android-release@v1
        with:
          releaseDirectory: app/build/outputs/bundle/release
          signingKeyBase64: ${{ secrets.KEYSTORE }}
          alias: ${{ secrets.KEY_ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}

      - name: Make artifact
        uses: actions/upload-artifact@v2
        with:
          name: '${{ env.app_name }}-${{ env.version_code }}-signed'
          path: ${{steps.sign_aab.outputs.signedReleaseFile}}


      - name: Build Changelog
        id: changelog
        uses: ardalanamini/auto-changelog@v3
        with:
          mention-authors: false
          mention-new-contributors: false
          include-compare: false
          semver: false

      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: '${{ env.app_name }}-${{ env.version_code }}'
          path: app/build/outputs/apk/debug/app-debug.apk

      - name: Upload S3
        uses: shallwefootball/s3-upload-action@master
        id: s3
        with:
            aws_key_id: ${{ secrets.AWS_KEY_ID }}
            aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
            aws_bucket: ${{ secrets.AWS_BUCKET }}
            source_dir: app/build/outputs/apk/debug/
