name: Sign APK

on:
  push:
    branches:
      - main # Adjust this to your main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle

      - name: Install OpenJDK
        run: sudo apt-get install -y openjdk-11-jdk

      - name: Install Android SDK
        uses: android-actions/setup-android@v2
        with:
          sdk-version: '31.0.0' # Replace with your desired SDK version

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build APK
        run: ./gradlew assembleRelease

      - name: Retrieve PK8 and PEM from secrets
        run: |
          echo "$PLATFORM_PK8" | base64 -d > keystore.pk8
          echo "$PLATFORM_PEM" | base64 -d > keystore.pem

      - name: Retrieve keystore alias and password from secrets
        env:
          KEYSTORE_ALIAS: ${{ secrets.KEYSTORE_ALIAS }}
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
        run: |
          echo "KEY_ALIAS=${KEY_ALIAS}" >> $GITHUB_ENV
          echo "KEY_STORE_PASSWORD=${KEY_STORE_PASSWORD}" >> $GITHUB_ENV

      - name: Sign APK
        run: |
          jarsigner -verbose -sigalg SHA1withRSA -digestalg SHA1 -keystore platform.pk8 -storepass ${{ env.KEY_STORE_PASSWORD }} app-release-unsigned.apk ${{ env.KEY_ALIAS }}
      - name: Verify and Align APK
        run: |
                zipalign -v 4 app-release-unsigned.apk app-release-signed-aligned.apk
                mv app-release-signed-aligned.apk app-signed.apk