name: Sign test APK

on:
  push:
    branches:
      - test # Adjust this to your main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build APK
        run: ./gradlew assembleRelease

      - name: Download and Install apksigner
        run: |
          sdkmanager "build-tools;30.0.3"

      - name: Sign APK
        run: |
          echo "${{ secrets.PLATFORM_PK8 }}" | base64 -d > key.pk8
           echo "${{ secrets.PLATFORM_PEM }}" | base64 -d > key.pem
          
      - name: Debugging Info
        run: |
          echo "KEYSTORE_PK8:"
          echo "${{ secrets.PLATFORM_PK8 }}"
          echo "KEYSTORE_PEM:"
          echo "${{ secrets.PLATFORM_PEM }}"

      - name: Sign APK using apksigner
        run: |
            export PATH="$PATH:$ANDROID_HOME/build-tools/30.0.3"  # Update <version> with the appropriate build tools version
            apksigner sign --ks key.pk8 --ks-pass pass:"" --out app/build/outputs/apk/release/app-release-signed.apk app/build/outputs/apk/release/app-release-unsigned.apk
      

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: signed-apk
          path: app/build/outputs/apk/release/app-release-signed.apk
