Skip to content
Abubakaryounas
/
github-actions-demo

Type / to search

Code
Issues
Pull requests
Actions
Projects
Wiki
Security
Insights
Sign Debug APK
Test # 4 #29
Jobs
Run details
Workflow file for this run
.github/workflows/dummy.yml at 53e65ca
name: Sign Debug APK

on:
  push:
    branches:
      - main # Adjust this to your main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build Debug APK
        run: ./gradlew assembleDebug

      - name: Download and Install apksigner
        run: |
          sdkmanager "build-tools;30.0.3"
      - name: Decode Keystore
        run: |
          echo ${{ secrets.KEYSTORE }} | base64 -d > keystore.jks
      - name: Sign Debug APK
        run: |
          jarsigner -verbose -sigalg SHA1withRSA -digestalg SHA1 -keystore app/build/outputs/apk/debug/keystore.jks -storepass ${{ secrets.KEY_STORE_PASSWORD }} -keypass ${{ secrets.KEY_PASSWORD }} app/build/outputs/apk/debug/app-debug.apk ${{ secrets.KEY_ALIAS }}
          $ANDROID_SDK_ROOT/build-tools/30.0.3/zipalign -v 4 app-debug.apk app-debug-signed.apk
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: signed-debug-apk
          path: app/build/outputs/apk/debug/app-debug-signed.apk
