name: Sign Debug APK

on:
  push:
    branches:
      - main # Adjust this to your main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build Debug APK
        run: ./gradlew assembleDebug

      - name: Download and Install apksigner
        run: |
          sdkmanager "build-tools;33.0.1"
      - name: Decode Keystore
        run: |
          echo ${{ secrets.KEYSTORE }} | base64 -d > keystore.jks
      - name: Sign Debug APK
        run: |
          apksigner sign --key platform.pk8 --cert platform.x509.pem app/build/outputs/apk/debug/app-debug.apk
        
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: signed-debug-apk
          path: app/build/outputs/apk/debug/app-debug-signed.apk
