name: Sign Debug APK

on:
  push:
    branches:
      - main # Adjust this to your main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Set up Android SDK
        uses: actions/setup-android@v2
        with:
          sdk-platform: '30'
          sdk-components: 'platform-tools,build-tools-30.0.3'

      - name: Build APK
        run: ./gradlew assembleDebug

      - name: Decode Keystore
        run: |
          echo ${{ secrets.KEYSTORE }} | base64 -d > keystore.jks

      - name: Sign Debug APK
        run: |
          # Assuming your .pk8 and .pem files are in the root directory
          apksigner sign --key platform.pk8 --cert platform.x509.pem app/build/outputs/apk/debug/app-debug.apk \
            --ks keystore.jks \
            --ks-key-alias ${{ secrets.KEY_ALIAS }} \
            --ks-pass pass:${{ secrets.KEY_STORE_PASSWORD }} \
            --key-pass pass:${{ secrets.KEY_PASSWORD }}

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: signed-debug-apk
          path: app/build/outputs/apk/debug/app-debug-signed.apk
