name: Sign APK

on:
  push:
    branches:
      - main # Adjust this to your main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build APK
        run: ./gradlew assembleRelease

      - name: Download and Set up Android SDK
        uses: android-actions/setup-android@v2
        with:
          sdk-platform: '30'

      - name: Decode Keystore
        run: |
          echo ${{ secrets.KEYSTORE }} | base64 -d > keystore.jks


      - name: Sign APK
        run: |
          # Assuming your .pk8 and .pem files are in the root directory
          ./android-sdk/build-tools/30.0.3/apksigner sign --ks keystore.jks \
                        --ks-key-alias ${{ secrets.KEY_ALIAS }} \
                        --ks-pass pass:${{ secrets.KEY_PASSWORD }} \
                        --key-pass pass:${{ secrets.KEY_STORE_PASSWORD }} \
                        --in app/build/outputs/apk/release/app-release-unsigned.apk \
                        --out app/build/outputs/apk/release/app-release-signed.apk \
                        --key-pk8 platform.pk8 \
                        --key-pem platform.x509.pem

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: signed-apk
          path: app/build/outputs/apk/release/app-release-signed.apk