name: Sign Debug APK

on:
  push:
    branches:
      - main # Adjust this to your main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Download Android SDK
        run: wget https://dl.google.com/android/repository/commandlinetools-linux-7302050_latest.zip
      - name: Unzip Android SDK
        run: unzip commandlinetools-linux-7302050_latest.zip -d $HOME/android-sdk
      - name: Export Android SDK path
        run: |
          echo "export ANDROID_SDK_ROOT=$HOME/android-sdk" >> $HOME/.bashrc
          source $HOME/.bashrc

      - name: Accept Android licenses
        run: yes | $ANDROID_SDK_ROOT/cmdline-tools/bin/sdkmanager --licenses

      - name: Install Android Build Tools
        run: $ANDROID_SDK_ROOT/cmdline-tools/bin/sdkmanager "build-tools;30.0.3"

      - name: Build APK
        run: ./gradlew assembleDebug

      - name: Decode Keystore
        run: |
          echo ${{ secrets.KEYSTORE }} | base64 -d > keystore.jks

      - name: Sign Debug APK
        run: |
          # Assuming your .pk8 and .pem files are in the root directory
          apksigner sign --key file.pk8 --cert file.pem app/build/outputs/apk/debug/app-debug.apk

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: signed-debug-apk
          path: app/build/outputs/apk/debug/app-debug-signed.apk
